51/process messages from client
Miol-Mor/battle-game pull request #57
Opened 2020-08-06 19:30 UTC by Hairash

#51

2020-08-09 12:48 UTC, bronvic commented
> Really beautiful.
> But what about tests?

There are two places that have not been tested:
* handle function 
* new and from_str functions from /api/*


About handle
I don't know how to test it using unit tests (I suppose there is a way by imitating request from server to websocket)
But most importantly that all this staff with switch function will be removed very soon and we will have game instance shared between all connections and this instance will process commands. Thus tests which we'll write now becomes invalid

About other little functions
There is .unwrap almost everywhere and this is something we don't want in production. I think we have to work on error handling and after that write tests for this folks

2020-08-26 17:23 UTC, alex-eg requested changes

2020-08-26 17:23 UTC, alex-eg commented on frontend/src/game.js
> +                // // and more simulation of server activity
Remove commented code.

2020-08-26 18:08 UTC, Hairash commented on frontend/src/game.js
> +                // // and more simulation of server activity
removed

2020-08-27 15:12 UTC, alex-eg approved these changes

2020-08-27 15:12 UTC, merged